version: 2.1
orbs:
  node: circleci/node@2.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test:
        version: 12.16.0
      - build-and-test:
        version: 10.19.0
      - build-and-test:
        version: 8.17.0
